### ISSUE TITLE
Incompatability with Propshaft 1.3.1

### ISSUE THREAD

**Issue by james-caresnap** [reactjs/react-rails#1358]
After upgrading Propshaft from 1.2.1 to 1.3.1, rails can no longer start:
```
/Users/some_user/.gem/ruby/3.4.4/gems/react-rails-3.2.1/lib/react/rails/railtie.rb:81:in 'block in <class:Railtie>': undefined method 'version' for an instance of Propshaft::Assembly (NoMethodError)

          sprockets_env.version = [sprockets_env.version, "react-#{asset_variant.react_build}"].compact.join("-")
                                                ^^^^^^^^
        from /Users/some_user/.gem/ruby/3.4.4/gems/railties-8.0.3/lib/rails/initializable.rb:32:in 'BasicObject#instance_exec'
        from /Users/some_user/.gem/ruby/3.4.4/gems/railties-8.0.3/lib/rails/initializable.rb:32:in 'Rails::Initializable::Initializer#run'
        from /Users/some_user/.gem/ruby/3.4.4/gems/railties-8.0.3/lib/rails/initializable.rb:61:in 'block in Rails::Initializable#run_initializers'
        from /Users/some_user/.gem/ruby/3.4.4/gems/tsort-0.2.0/lib/tsort.rb:231:in 'block in TSort.tsort_each'
        from /Users/some_user/.gem/ruby/3.4.4/gems/tsort-0.2.0/lib/tsort.rb:353:in 'block (2 levels) in TSort.each_strongly_connected_component'
        from /Users/some_user/.gem/ruby/3.4.4/gems/tsort-0.2.0/lib/tsort.rb:434:in 'TSort.each_strongly_connected_component_from'
        from /Users/some_user/.gem/ruby/3.4.4/gems/tsort-0.2.0/lib/tsort.rb:352:in 'block in TSort.each_strongly_connected_component'
        from /Users/some_user/.gem/ruby/3.4.4/gems/tsort-0.2.0/lib/tsort.rb:350:in 'Rails::Initializable::Collection#each'
        from /Users/some_user/.gem/ruby/3.4.4/gems/tsort-0.2.0/lib/tsort.rb:350:in 'Method#call'
        from /Users/some_user/.gem/ruby/3.4.4/gems/tsort-0.2.0/lib/tsort.rb:350:in 'TSort.each_strongly_connected_component'
        from /Users/some_user/.gem/ruby/3.4.4/gems/tsort-0.2.0/lib/tsort.rb:229:in 'TSort.tsort_each'
        from /Users/some_user/.gem/ruby/3.4.4/gems/tsort-0.2.0/lib/tsort.rb:208:in 'TSort#tsort_each'
        from /Users/some_user/.gem/ruby/3.4.4/gems/railties-8.0.3/lib/rails/initializable.rb:60:in 'Rails::Initializable#run_initializers'
        from /Users/some_user/.gem/ruby/3.4.4/gems/railties-8.0.3/lib/rails/application.rb:444:in 'Rails::Application#initialize!'
        from /Users/some_user/src/caresnap/evv-service/config/environment.rb:5:in '<main>'
        from /Users/some_user/src/caresnap/evv-service/test/test_helper.rb:9:in 'Kernel#require_relative'
        from /Users/some_user/src/caresnap/evv-service/test/test_helper.rb:9:in '<main>'
        from /Users/some_user/.rubies/ruby-3.4.4/lib/ruby/3.4.0/bundled_gems.rb:82:in 'Kernel.require'
        from /Users/some_user/.rubies/ruby-3.4.4/lib/ruby/3.4.0/bundled_gems.rb:82:in 'block (2 levels) in Kernel#replace_require'
        from /Users/some_user/.gem/ruby/3.4.4/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in 'Kernel#require'
        from /Users/some_user/src/caresnap/evv-service/test/components/agency_branch_component_test.rb:1:in '<main>'
        from /Users/some_user/.rubies/ruby-3.4.4/lib/ruby/3.4.0/bundled_gems.rb:82:in 'Kernel.require'
        from /Users/some_user/.rubies/ruby-3.4.4/lib/ruby/3.4.0/bundled_gems.rb:82:in 'block (2 levels) in Kernel#replace_require'
        from /Users/some_user/.gem/ruby/3.4.4/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in 'Kernel#require'
        from /Users/some_user/.gem/ruby/3.4.4/gems/railties-8.0.3/lib/rails/test_unit/runner.rb:66:in 'block in Rails::TestUnit::Runner.load_tests'
        from /Users/some_user/.gem/ruby/3.4.4/gems/railties-8.0.3/lib/rails/test_unit/runner.rb:64:in 'Array#each'
        from /Users/some_user/.gem/ruby/3.4.4/gems/railties-8.0.3/lib/rails/test_unit/runner.rb:64:in 'Rails::TestUnit::Runner.load_tests'
        from /Users/some_user/.gem/ruby/3.4.4/gems/railties-8.0.3/lib/rails/test_unit/runner.rb:56:in 'Rails::TestUnit::Runner.run'
        from /Users/some_user/.gem/ruby/3.4.4/gems/railties-8.0.3/lib/rails/commands/test/test_command.rb:33:in 'Rails::Command::TestCommand#perform'
        from /Users/some_user/.gem/ruby/3.4.4/gems/thor-1.4.0/lib/thor/command.rb:28:in 'Thor::Command#run'
        from /Users/some_user/.gem/ruby/3.4.4/gems/thor-1.4.0/lib/thor/invocation.rb:127:in 'Thor::Invocation#invoke_command'
        from /Users/some_user/.gem/ruby/3.4.4/gems/railties-8.0.3/lib/rails/command/base.rb:178:in 'Rails::Command::Base#invoke_command'
        from /Users/some_user/.gem/ruby/3.4.4/gems/thor-1.4.0/lib/thor.rb:538:in 'Thor.dispatch'
        from /Users/some_user/.gem/ruby/3.4.4/gems/railties-8.0.3/lib/rails/command/base.rb:73:in 'Rails::Command::Base.perform'
        from /Users/some_user/.gem/ruby/3.4.4/gems/railties-8.0.3/lib/rails/command.rb:65:in 'block in Rails::Command.invoke'
        from /Users/some_user/.gem/ruby/3.4.4/gems/railties-8.0.3/lib/rails/command.rb:143:in 'Rails::Command.with_argv'
        from /Users/some_user/.gem/ruby/3.4.4/gems/railties-8.0.3/lib/rails/command.rb:63:in 'Rails::Command.invoke'
        from /Users/some_user/.gem/ruby/3.4.4/gems/railties-8.0.3/lib/rails/commands.rb:18:in '<main>'
        from /Users/some_user/.rubies/ruby-3.4.4/lib/ruby/3.4.0/bundled_gems.rb:82:in 'Kernel.require'
        from /Users/some_user/.rubies/ruby-3.4.4/lib/ruby/3.4.0/bundled_gems.rb:82:in 'block (2 levels) in Kernel#replace_require'
        from /Users/some_user/.gem/ruby/3.4.4/gems/bootsnap-1.18.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in 'Kernel#require'
        from bin/rails:4:in '<main>'
```
