### ISSUE TITLE
Let's talk about Rails 3.2 -- Problem with precompiled assets and server rendering

### ISSUE THREAD

**Issue by jordanbyron** [reactjs/react-rails#483]
Hi everyone!

Sorry if this comes across as a silly question, but I'm seeing mixed messages about Rails 3.2 support and want to get a definitive answer. Based on my limited testing it seems nearly everything in Rails 3.2 works _except_ server rendering (ala `prerender: true`) with precompiled assets. I was a bit surprised to find out that there was a known issue with loading the manifest file in 3.2 (see [this comment](https://github.com/reactjs/react-rails/blob/master/test/react/server_rendering/manifest_container_test.rb#L3-L4) for more details). This all started when I got a `undefined method 'assets_manifest'` error In production and started digging into the source. 

As far as I can tell there isn't anything listed in the README about this limitation and I'm just looking to get a sense of how well supported Rails 3.2 is by the project's maintainers. I realize 3.2 is nearing its end of life, so perhaps this is a good time to reevaluate its support. I'd hate for someone else to get as deeply invested in using this gem, like I did, only to find out one of its core features doesn't work in production. :disappointed: 

That all being said I'd love to come up with a solution to this issue. I'm not terribly familiar with the internals of the asset pipeline but if there is some way to get this feature working in 3.2 I don't mind rolling up my sleeves and getting it done with a little guidance.

Thanks for all of your awesome work. I really appreciate it :sunflower:

**Comment by rmosolgo** [comment]
Ever since I inherited this project, it said "supports Rails 3.2", and I'm still on board for that! We have a Rails 3.2 gemfile, so we _mean_ to support it! 

I think the problem is: 
- `SprocketsRender` looks for `config.assets.compile`. If it's false, it uses the asset manifest ([src](https://github.com/reactjs/react-rails/blob/master/lib/react/server_rendering/sprockets_renderer.rb#L62-L66))
- Apparently that assumption is not safe for Rails 3.2! We must have another way to handle Rails 3.2.
- This wasn't covered by the tests ... when I got to this problem, I just skipped it, sorry! :grimacing:  ([src](https://github.com/reactjs/react-rails/blob/master/test/react/server_rendering/manifest_container_test.rb#L5))

So, I can think of a few ways to work around this: 

- Use `EnvironmentContainer` even when assets are precompiled. This kind of stinks because it compiles assets on the fly in production. But this is how react-rails worked until 1.6.0! You could do this by assigning `React::ServerRendering::SprocketsRenderer.asset_container_class = React::ServerRendering::EnvironmentContainer`. In that case, it will use the custom-defined `asset_container_class` instead of `ManifestContainer`. 
- Make another asset container class for the renderer to get files from. This is the _best_ thing to do, but I'm not exactly sure how it would work. 

I think you'd want to: 

- make a `server_rendering.js` manifest which includes `react-server`, components, and dependencies (this will be the default in a future react-rails version, [example](https://github.com/reactjs/react-rails/pull/471/files#diff-1c634efb0456410cda196c93082979e3R1))
- tell SprocketsRenderer to only load `server_rendering.js`: 

  ```ruby 
    config.react.server_renderer_options = {
      files: ["server_rendering.js"]
    }
  ```
- implement an asset container which implements `#find_asset("server_rendering.js")` to return the _compiled_ output of that manifest file. (`EnvironmentContainer` will do that, but it will compile the asset on the first load!)
- assign that asset container class to `React::ServerRendering::SprocketsRenderer.asset_container_class` 


All that to say, I think it's within the realm of possibility, but I'm not sure how to get the _already-compiled_ contents of that file in Rails 3.2. How can you find the file if you don't know the digest? Could you grep the directory for  `server_rendering*.js` ?

**Comment by jordanbyron** [comment]
@rmosolgo dude you rock :metal: Super fast response and amazingly detailed :+1: 

This gives me a much better idea of what needs to happen and at the very least gives me a workaround in the meantime. Do you think it would be beneficial for others if we added a little caveat to the "Server Rendering" section of the `README` about the current limitations of 3.2? If so I'd be happy to draft something up.

**Comment by rmosolgo** [comment]
go for it!

**Comment by jordanbyron** [comment]
@rmosolgo I think I've got this working. Here is the solution I came up with based on your suggestions:

```ruby
class YamlManifestContainer
  def initialize
    data = YAML.load_file(Rails.root.join("public/assets/manifest.yml"))

    @manifest = OpenStruct.new(
      assets: data,
      dir:    'assets'
    )
  end

  def find_asset(logical_path)
    asset_path = @manifest.assets[logical_path] || raise("No compiled asset for #{logical_path}, was it precompiled?")
    asset_full_path = ::Rails.root.join("public", @manifest.dir, asset_path)
    File.read(asset_full_path)
  end
end
```

`YamlManifestContainer` mimics the behavior of `React::ServerRendering::ManifestContainer` and internally generates an stand in object that acts like `Sprockets::Manifest`. Rails 3.2 outputs manifest files in `yaml` format, not JSON like Rails 4+, so I couldn't use `Sprockets::Manifest` to parse the manifest file. Instead we create a struct which quacks like a `Sprockets::Manifest` and parses the `manifest.yml` file.

```ruby
if Rails.application.config.assets.compile == false
  React::ServerRendering::SprocketsRenderer.asset_container_class =
    YamlManifestContainer
end
```

I threw this into an initializer so when we are in development, or any env where `config.assets.compile` is `false` we get the default behavior which recompiles the assets on demand. Otherwise it uses the fancy new `YamlManifestContainer` class which pulls the precompiled assets instead.

Lastly, I created a `server_rendering.js` file that looked just like the example you gave and made sure to add it to `config.assets.precompile` and `config.react.server_renderer_options`

---

And viola! Working server rendering with precompiled assets. I'm not sure how robust my assumptions are about the manifest file and assets location. Any insights on how I could improve those lines of `YamlManifestContainer`?

Lastly if you think this approach is a solid solution I'd be happy to workup a PR integrating these changes into the library. Thanks again for all of your help! :fire_engine:

**Comment by rmosolgo** [comment]
:tada: :moneybag: That's awesome! It'd be great to get this into `react-rails`, I was just thinking about cutting 1.6.1, maybe this could be in it. 


I think you could add some logic here to use YamlManifestContainer: 

https://github.com/reactjs/react-rails/blob/master/lib/react/server_rendering/sprockets_renderer.rb#L64

```ruby
elsif Rails::VERSION::MAJOR == 3 
  YamlManifestContainer.new 
else 
  # ... 
```

As far as improving YamlManifestContainer, is there an advantage to creating `@manifest` instead of accessing the parsed YAML directly? For example,

```ruby
class YamlManifestContainer
  def initialize
    @assets = YAML.load_file(Rails.root.join("public/assets/manifest.yml"))
  end

  def find_asset(logical_path)
    asset_path = @assets[logical_path] || raise("No compiled asset for #{logical_path}, was it precompiled?")
    asset_full_path = ::Rails.root.join("public", "assets", asset_path)
    File.read(asset_full_path)
  end
end
```

?


Then, if you wanted to add unit tests, that'd be great. You could: 

- Setup a mock asset situation: 
  - Add `public/assets/manifest.yml` to the Rails app in `tests/dummy` 
  - Add a pretend compiled asset in `public/assets` and a corresponding entry in `manifest.yml`
- Add `yaml_manifest_directory_test.rb` next to `manifest_container_test.rb`
- Assert that `find_asset(your_asset_name)` returns the file you put in `public/assets`

But, to be honest, that might be more trouble than it's worth! The operation is quite straightforward, you'd practically be testing the Ruby standard library. Do you have and links to documentation handy? If we can be relatively confident that this covers the default setup for Rails 3.2, I think we could skip the  tests.

**Comment by jordanbyron** [comment]
> I think you could add some logic here to use YamlManifestContainer:

That's exactly what I was thinking!

> As far as improving YamlManifestContainer, is there an advantage to creating @manifest instead of accessing the parsed YAML directly?

Totally! Originally I tried subclassing `React::ServerRendering::ManifestContainer` to get the `find_asset` method for free but was running into issues so I abandoned that approach and the resulting `@manifest` code never got cleaned up. 

> Then, if you wanted to add unit tests, that'd be great. 

Of course! I'll get that added to my PR so we can be sure this is covered. 

> Do you have any links to documentation handy?

Unfortunately I don't, but I'll see what I can dig up. Regardless I'll make sure this is passing in the test suite so we can be fairly confident it works with a stock Rails 3.2 app.

Thanks again for the awesome feedback. I'll try to get this out to you tonight or tomorrow morning. :hammer:
