### ISSUE TITLE
Server-side rendering is not working with sprockets-rails 3.0

### ISSUE THREAD

**Issue by oleglitvin** [reactjs/react-rails#443]
In sprockets-rails 3.0 `Rails.application.assets` is disabled when `config.assets.compile=false` (https://github.com/rails/sprockets-rails/pull/220).
And `React::ServerRendering::SprocketsRenderer` is failing on production environment at [this line](https://github.com/reactjs/react-rails/blob/122ae3e0f5595254db0b292e19c9994ebc1f069c/lib/react/server_rendering/sprockets_renderer.rb#L14), with `undefined method '[]' for nil:NilClass`

**Comment by oleglitvin** [comment]
OK, there is an opened pull-request https://github.com/reactjs/react-rails/pull/430/files

**Comment by rmosolgo** [comment]
Could you give that branch a try? Let me know if it works for you -- it looks good to me but I'd like a second opinion before I merge it!

**Comment by inchr** [comment]
I need this too :( I will test your PR very soon @rmosolgo ! Thanks for your work!!

**Comment by DTwigs** [comment]
This would be super helpful!

**Comment by oleglitvin** [comment]
> Could you give that branch a try? Let me know if it works for you -- it looks good to me but I'd like a second opinion before I merge it!

@rmosolgo yep, it works!

**Comment by oleglitvin** [comment]
It fails at this line https://github.com/reactjs/react-rails/pull/430/files#diff-543f6fa05678c006b8d4baa5cd4b517cR13, not being able to find `react-server.js` (even if react-server was added to the `config.assets.precompile` and being precompiled)

**Comment by djforth** [comment]
+1

**Comment by dbackeus** [comment]
+1

**Comment by rmosolgo** [comment]
Could you try react-rails 1.6.0? It includes #430 which was my first try at fixing this

**Comment by tirdadc** [comment]
I can confirm that I have this issue in production with 1.6.0 when server-side rendering is used.

`ActionView::Template::Error (No compiled asset for react-server.js, was it precompiled?):`

**Comment by rmosolgo** [comment]
Ok, thanks, let me try to track that down!

**Comment by rmosolgo** [comment]
Ohh strange. When it creates the manifest, the manifest has `production/react-server` instead of `react-server`. Then, SprocketsRenderer fails to find `react-server` since it has a different logical path. 

I found a workaround: 

1. Make sure components.js is compiled (`Rails.application.config.assets.precompile += %w( components.js )`)
1. Add `//= require react-server` to your components.js file 
1. Specify _only_ components.js for server rendering: 

  ```ruby 
    config.react.server_renderer_options = {
      files: ["components.js"], # files to load for prerendering
    }
  ```

This way, it bundles react-server into components.js, it doesn't look it up when you try to render a page! 

I'll look for a proper fix tonight or tomorrow!

**Comment by dudeman** [comment]
We didn't want the react-server code to end up in the components.js since that's delivered to browser clients. So we created a components-server.js file containing:
```
//= require react-server
```
And then added that components-server.js file to the server_rendering_options:
```
config.react.server_renderer_options = {
    files: ["components-server.js", "components.js"], # files to load for prerendering
  }
```

This seemed to fix the prerendering asset location error above. However, we then were getting an error because of an additional sprockets 3 incompatibility. PR for that is here https://github.com/reactjs/react-rails/pull/478

**Comment by oleglitvin** [comment]
It seems that #471 fixes this issue. The only thing that needs to be done is to add server_rendering.js to the `Rails.application.config.assets.precompile` list.

**Comment by rmosolgo** [comment]
Maybe i should add that to `rails generate react:install`, but add `--skip-server-rendering` if you don't want the JS manifest & initializer

**Comment by oleglitvin** [comment]
Sounds good)

**Comment by alcedo** [comment]
i'm using `gem 'react-rails', "~> 1.6.0"` but am still encountering the above error. eg: 

http://cl.ly/1m2y3B1N3f1j

any ideas?

**Comment by rmosolgo** [comment]
This patch isn't merged yet because it'll be a breaking change. 

Did you try the workaround described here? https://github.com/reactjs/react-rails/issues/443#issuecomment-180544359

**Comment by alcedo** [comment]
Hmm.. although it doesnt work. Here's a screenshot of my change:  http://cl.ly/2c3O3s343Y3k 

except that in my changes, instead of using `server_rendering.js`

im just doing:
```
config.react.server_renderer_options = {
    files: ["components.js"], # files to load for prerendering
}```

and adding this line in components.js

```
//= require react-server
```

**Comment by rmosolgo** [comment]
> doesnt seem to work

Can you elaborate? For example, did you get an error? What was the message & stack trace? 

Also, did you restart your development server after changing the configurations?

**Comment by benben** [comment]
The workaround didn't help me either.

```
2016-03-03T19:42:59.810190+00:00 app[web.1]: Completed 500 Internal Server Error in 13ms (ActiveRecord: 0.6ms)
2016-03-03T19:42:59.812302+00:00 app[web.1]:
2016-03-03T19:42:59.812312+00:00 app[web.1]: ActionView::Template::Error (No compiled asset for react-server.js, was it precompiled?):
2016-03-03T19:42:59.812313+00:00 app[web.1]:     33:   %fieldset.form__fieldset
2016-03-03T19:42:59.812314+00:00 app[web.1]:     34:     %legend.form__legend
2016-03-03T19:42:59.812314+00:00 app[web.1]:     35:       Releases
2016-03-03T19:42:59.812316+00:00 app[web.1]:     36:     = react_component 'MultiFieldForm', {parent: 'system', component: 'Release', fields: @system.releases.to_json}, { prerender: true }
```

**Comment by rmosolgo** [comment]
Weird! It shouldn't even be looking for `react-server` anymore since we override that value with 

```ruby
  config.react.server_renderer_options = {
    files: ["server_rendering.js"], # files to load for prerendering
  }
```

:crying_cat_face:

**Comment by rmosolgo** [comment]
(Usually, it's the default provided here: https://github.com/reactjs/react-rails/blob/master/lib/react/server_rendering/sprockets_renderer.rb#L18)

**Comment by benben** [comment]
just to be clear: I put the `config.react.server_renderer_options` in my application.rb

**Comment by brettjurgens** [comment]
i'm getting this as well with
```
rails 4.2.6
ruby 2.2.3p173
sprockets 3.5.2
```

```
ActionView::Template::Error (No compiled asset for react-server.js, was it precompiled?):
    2: .card-login-container
    3:   .card.card-login
    4:     = react_component('LoginForm', { login_url: create_session_path }, { prerender: true })
  app/views/sessions/new.html.haml:4:in `_app_views_sessions_new_html_haml___2128502748164763252_70237860093020'
```

**Comment by rmosolgo** [comment]
@brettjurgens could you share your file setup? That is, which files do you pass to `config.react.server_renderer_options` & what do they `//= require`?

**Comment by brettjurgens** [comment]
@rmosolgo my bad, ignore me :disappointed:

**Comment by ruiafonsopereira** [comment]
Same here. Here's the Heroku log:
```
ActionView::Template::Error (No compiled asset for react-server.js, was it precompiled?):
     4: %p
     5:   The time is now: #{Time.now}
     6:
     7: = react_component('HelloFromReact', {name: 'RAP'}, {prerender: true})
  app/views/dashboard/index.html.haml:7:in `_app_views_dashboard_index_html_haml___3362025122456778176_70295050466140'
```
Heroku's running on:
```
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
Rails 4.2.6
gem 'react-rails', '~> 1.6'
```

**Comment by BunHouth** [comment]
+1
I'm also get the same problem 

```
ActionView::Template::Error (No compiled asset for react-server.js, was it precompiled?):
    1: = react_component('Products', {}, { prerender: true })
  app/views/products/index.html.haml:1:
in `_app_views_products_index_html_haml__2224966273559460328_68268360'
```

gem 'react-rails',                        '~> 1.6', '>= 1.6.2'

**Comment by alcedo** [comment]
ive updated to the latest version, 

`gem 'react-rails', '~>1.7.1'`

but still the same error:

```
A, [2016-05-19T09:12:22.942353 #58]   ANY -- : 2016-05-19 09:12:22 +0000 severity=FATAL, ActionView::Template::Error (No compiled asset for react-server.js, was it precompiled?):
    19:   }
    20: </style>
    21: <%=
    22:     react_component(
    23:       'myfolder.BaseComponent',
    24:       @view_model.merge({csrf: form_authenticity_token}),
    25:       {prerender: true}
  app/views/product_display/index.html.erb:22:in `_app_views_product_display_index_html_erb___3690161152355483093_69863808921520'
```

**Comment by tirdadc** [comment]
Confirming that the [workaround](https://github.com/reactjs/react-rails/issues/443#issuecomment-180544359) works with 1.7.1.

I tried to get a component that uses [moment.js](http://momentjs.com/) in its `getInitialState()` to pre-render once I set this up and also added `//= require moment.js` to `server_rendering.j`s, but I still got an error:

```
Encountered error "ReferenceError: moment is not defined" when prerendering Calendar
```
Anything else I need to do to get that to work?

**Comment by alcedo** [comment]
hmm did u put //= require moment above your component definition?

**Comment by krazyjakee** [comment]
Does server_rendering.js go in `/assets/javascripts/server_rendering.js`?

We're getting...
```
ActionView::Template::Error: No compiled asset for server_rendering.js, was it precompiled?
No compiled asset for components.js, was it precompiled?
```

**Comment by alcedo** [comment]
@krazyjakee did you add server_rendering.js into the asset precompile list?

**Comment by krazyjakee** [comment]
@alcedo yes, it is definitely there.

**Comment by alcedo** [comment]
@krazyjakee 

my server_rendering.js goes into /assets/javascripts/server_rendering.js 

and this is the content of it, if its of any help.

```
//= require react
//= require react-server
//= require react_bootstrap
//= require components

```

**Comment by krazyjakee** [comment]
@alcedo mine was...
```
//= require react-server
//= require react_ujs
//= require components
```

I'll tweak it and get back to you. Thanks!

**Comment by alcedo** [comment]
no problem. and i think you probably wont need react_ujs, since its only used on client side.

**Comment by rafaelv90** [comment]
Did the workaround!

But now I get the same error with `server_rendering.js`

`RuntimeError (No compiled asset for server_rendering.js, was it precompiled?):`

Rails 4.2.6
ruby 2.3.1p112
sprockets 3.6.2
react-rails 1.8.0

**Comment by rmosolgo** [comment]
To confirm, did you add `server_rendering.js` to your list of precompiled assets, something like 

```ruby
Rails.application.config.assets.precompile += %w(server_rendering.js)
```
 
?

**Comment by rafaelv90** [comment]
Yes! Did all the steps you provided!
It's strange because it works in development mode and worked in production until some days ago. And it seems a lot of people is having the same issue. Perhaps any conflict with other dependency gems?

I'm still trying to find out!

**Comment by rmosolgo** [comment]
> until some days ago

woah, how strange?! did anything else change in your app at that time?

**Comment by rafaelv90** [comment]
I'm trying to figure out! Looking through the commits, updated some code and added only a few gems, but nothing related to React itself.
Added `pundit` gem and pointed another one (`validates_cpf_cnpj`) to a Github fork repo.

But I don't believe these changes are related with this rendering issue.

**Comment by JoelBeasley** [comment]
@rafaelv90 I'm experiencing the same thing, worked fine in production, still works in dev but today stopped working in production.

**Comment by rmosolgo** [comment]
> stopped working in production

was it after a redeploy? or, it just started :boom:ing while running?

**Comment by JoelBeasley** [comment]
@rmosolgo after redeploy.

**Comment by rmosolgo** [comment]
Is the diff for that redeploy small enough to list the changes? For example: 

- Any gem updates?
- Ruby version update? 
- Application code update?
- Application configuration update?
- Server administration changes?

**Comment by JoelBeasley** [comment]
@rmosolgo The production code mirrored on staging worked, my mistake was viewing the production log and it was a process of the prior build, learned something new about EY.

I also found that when deploying on EngineYard the assets won't re-precomplie if the assets.rb is changed, only if the assets .js/.css are changed, or its in the EY config to always precomplie.

**Solution that worked for me**
Adding the assets to the precomplie, then touching the .js asset allowed it to precomplie and work.
`Rails.application.config.assets.precompile += %w( react-server.js components.js )`

Unfortunately I was not able to locate the differences that suddenly required the react-server.js components.js to be listed in the precomplie, I did check the gemlock files of both codebases and they are identical.

**Comment by rmosolgo** [comment]
Thanks for sharing your findings!!

**Comment by maveonair** [comment]
I can confirm that I only had to add `Rails.application.config.assets.precompile += %w( react-server.js components.js )` in  `config/initalizers/assets.rb` to get server side rendering work on Heroku.

**Comment by dimoreira** [comment]
Guys, in my scenario I use separated manifest files for loading dependencies and react components for main interface and admin interface.

My files are divided as following:

**application.js:**
```javascript
//= require jquery
//= require jquery_ujs
//= require bootstrap
//= require maskedinput
//= require jquery.fancybox
//= require getstream
//= require react
//= require react_ujs
//= require react-rails-hot-loader
//= require components
```

**server_rendering_components.js:**
```javascript
//= require react
//= require react-server
//= require components
```

**components.js:**
```javascript
//= require accounting.min
//= require moment-with-locales.min
//= require autosuggest
//= require_tree ./react

moment.locale('pt-br');
```

**admin.js:**
```javascript
//= require react
//= require react_ujs
//= require react-rails-hot-loader
//= require admin_components
```

**server_rendering_admin_components.js:**
```javascript
//= require react
//= require react-server
//= require admin_components
```

**admin_components.js:**
```javascript
//= require_tree ./admin-react
```

**config/environments/{development.rb,production.rb}"**
```ruby
config.react.server_renderer_options = {
    files: ['server_rendering_components.js, server_rendering_admin_components.js']
  }
```

**config/initializers/assets.rb:**
```ruby
Rails.application.config.assets.precompile += %w( admin.js admin.css server_rendering_components.js components.js server_rendering_admin_components.js admin_components.js )
```

I just keep getting this error:

> React::ServerRendering::PrerenderError - Encountered error "ReferenceError: ReactDOMServer is not defined" when prerendering *ComponentName*

What I'm doing wrong?

**Comment by dimoreira** [comment]
Nevermind guys, I just fix the files object to correction:

Instead of:

```ruby
config.react.server_renderer_options = {
    files: ['server_rendering_components.js, server_rendering_admin_components.js']
 }
```

Corrected for this:

```ruby
config.react.server_renderer_options = {
    files: ['server_rendering_components.js', 'server_rendering_admin_components.js']
 }
```

**Comment by rmosolgo** [comment]
Sounds like we have a couple of options here. Soon I'll merge #471 and remove the confusing defaults. Thanks for sharing your solutions!
